### PR TITLE
Drop css-minimizer-webpack-plugin 5 support, only css-minimizer-webpack-plugin 7 is supported

### PR DESCRIPTION
**Pull request by Kocal**
It also upgrade cssnano to ^7, see https://github.com/webpack-contrib/css-minimizer-webpack-plugin/blob/master/CHANGELOG.md#700-2024-05-07

### CODE REVIEW

**Comment by Kocal** [comment]
Failing checks due to Node.21 will be fixed by #1321, more work is needed for other checks.

**Comment by stof** [comment]
This requires bumping the min node version from 18.0.0 to 18.12.0 due to their BC break in 6.0

**Comment by stof** [comment]
The failures are probably not directly related to this PR. https://github.com/symfony/webpack-encore/pull/818 fails the "low dependencies" jobs while it only changes comments.

**Comment by stof** [comment]
I confirm that a build in the master branch also breaks there: https://github.com/symfony/webpack-encore/actions/runs/10666578054/job/29562308888

And #1322 seems to fix it.

**Pull request closed without merging**
