### PR TITLE
Feat/sass loader 8

### PR DESCRIPTION
**Pull request by weaverryan**
Fixes weird test issue for #736 - I'm trying to see if I can debug the "lowest" test failure.

It appears the problem is with Webpack > 4.22 and Vue < 2.5.0.

### CODE REVIEW

**Comment by weaverryan** [comment]
This is ready!

**Comment by Kocal** [comment]
Nice!

**Comment by weaverryan** [comment]
Thank you @Kocal!

**Comment by Kocal** [comment]
Thank you too! :)

**Pull request merged**
