### PR TITLE
Fix issue incorrect paths for fonts. Add methods to Use relative paths.

### PR DESCRIPTION
**Pull request by nikrou**
The idea is to allow to use relative path for fonts and/or images.

### CODE REVIEW

**Comment by nikrou** [comment]
@stof I saw after. I will fix it quickly. Sorry. Do my PR is still revelant or interesting ?

**Comment by stof** [comment]
@nikrou I don't know, because it is very hard for me to know what it actually does (as the diff shows these 100 commits)

**Comment by nikrou** [comment]
I don't know how to fix that mess. I fix the problem of rebase on my branch :
https://github.com/symfony/webpack-encore/compare/master...nikrou:issue-88

**Comment by Lyrkan** [comment]
Easiest way to do it would probably be to:

* create a new branch based on the problematic one (e.g. `issue-88` => `issue-88-copy`)
* remove the original branch __locally__ (`issue-88`)
* recreate it based on master
* cherry-pick your commits from the other branch you created earlier
* `git push -f`

But since Github doesn't seem to recognize your repository anymore (did you recreate it?) I'm not sure how to handle that...

By the way I left [a comment](https://github.com/symfony/webpack-encore/issues/88#issuecomment-335712249) in the related issue. Is adding `setFontsPublicPath()` and `setImagesPublicPath()` the right way to fix it?

**Comment by nikrou** [comment]
Yes I recreaed my repository. It doesn't seem to be a good idea ! :-(

**Comment by stof** [comment]
yeah, if you deleted you fork, you will have to create a new PR.

**Comment by nikrou** [comment]
My bad. I create another PR : #179

**Comment by Lyrkan** [comment]
Ok, let's close this one then.

**Pull request closed without merging**
