### PR TITLE
⬆️ Upgraded ts-loader to ^8.0.1

### LINKED ISSUE #703: Webpack Encore requires version ^5.3.0 of ts-loader. Your version 6.2.1 is too new.
This issue is a proposal/request to update supported version for `ts-loader`

When using `ts-loader` in my webpack + encore setup
Getting this warning on webpack build

```
Webpack Encore requires version ^5.3.0 of ts-loader. Your version 6.2.1 is too new. The related feature *may* still work properly. If you have issues, try downgrading the library, or upgrading Encore.
```

**Expected**: Webpack Encore works with `ts-loader` v6+ without warnings.

### PR DESCRIPTION
**Pull request by skmedix**
Resolves #703 

~~Tests: ✔️ [Node 10](https://github.com/skmedix/webpack-encore/runs/843779672?check_suite_focus=true) | ✔️ [Node 12](https://github.com/skmedix/webpack-encore/runs/843779686?check_suite_focus=true)~~

### CODE REVIEW

**Comment by stof** [comment]
> Typescript 2.x anymore

Typescript 2.x is EOLed since years.

**Review by deguif — APPROVED** [review]

**Comment by weaverryan** [comment]
Thanks @skmedix!

**Comment by NikoGrano** [comment]
@weaverryan @skmedix 

Using newer loader will cause encore throw a warning message about using too new version. However this PR doesn't seem to make any other changes than `package.json`.

Did you double check this will also remove the warning message posted during build?

**Comment by Kocal** [comment]
The `ts-loader` version is enforced in Encore (https://github.com/symfony/webpack-encore/blob/main/lib/features.js#L68), so:
- if you upgrade Encore and you use ts-loader < 8, you will have a warning message
- if you upgrade Encore and you already used ts-loader 8, everything will be fine
- if you upgrade Encore and ts-loader release a new major version (9) and you use it, you will have a warning message (as expected)

**Comment by miedzikd** [comment]
If I want use new ts-loader version what I should upgrade?
`symfony/webpack-encore-bundle` composer package or `@symfony/webpack-encore` npm module? Maybe both?

**Comment by miedzikd** [comment]
If I want use new ts-loader version what I should upgrade?
`symfony/webpack-encore-bundle` composer package or `@symfony/webpack-encore` npm module? Maybe both?

**Comment by weaverryan** [comment]
Actually, ts-loader should directly be in YOUR package.json file, so you can upgrade it directly - that’s all you need :)

**Comment by miedzikd** [comment]
Thanks @weaverryan for fast response... 
Right... I have ts-loader in my package.json... when I upgraded this package to version ^9.2.2 then I see: `Webpack Encore requires version ^8.0.0 of ts-loader (...)` warning. 
My idea was try to upgrade also `webpack-encore` ... but Im not sure what I should upgrade: composer package or npm module... 

But when I think about it now... I can actually update both :) I was just wondering if it enough to update only the npm module, or do I need to update composer package as well.

PS. I love your tutorials ;)

**Pull request merged**
