### PR TITLE
Update webpack-manifest-plugin.js

### PR DESCRIPTION
**Pull request by Detract**
Version 1.1.0 is outdated. It took me some time to figure out why configuration options like map and filter does not work with encore.

### CODE REVIEW

**Comment by Lyrkan** [comment]
Hi @Detract,

We're waiting for the new major version or webpack-manifest-plugin to be released (see #164) so we can remove that file and use the real plugin.

We needed that fork because of some issues that were directly patched in the file you modified and are should be fixed in v2.0.0 (currently in rc1, no idea if there is an ETA for a stable version, ping @mastilver). I guess these missing patches are the cause of the failing tests.

**Comment by Detract** [comment]
Hi @Lyrkan,

thanks for response. I'll then close the pr and wait for the new version.

Dirk

**Comment by mastilver** [comment]
Hi @Lyrkan 

I don't want to release v2 before https://github.com/danethurber/webpack-manifest-plugin/issues/100 is fixed, and I don't have much time at the moment, I will try later next week

**Comment by Lyrkan** [comment]
Hey @mastilver!

No worries, there is still some work to be done on #164 anyway :)

**Pull request closed without merging**
