### PR TITLE
Match `@vue/compiler-sfc` requirement with `vue`

### PR DESCRIPTION
**Pull request by dmaicher**
Fixes https://github.com/symfony/webpack-encore/issues/1165

### CODE REVIEW

**Comment by stof** [comment]
Why making it a draft PR ?

**Comment by dmaicher** [comment]
Do I need to fix the yarn fails?

**Comment by stof** [comment]
@Kocal any idea what those failures are about ? To me, it seems like yarn says it fails with errors without actually showing those errors.

**Comment by dmaicher** [comment]
Yeah I cannot fix those.

I tried

```
yarn set version berry
yarn install
```

generates a huge yarn.lock diff and still fails

**Comment by stof** [comment]
ah indeed. I missed that one of those symbols was a GHA group and not the Yarn prefix...

**Review by Kocal — APPROVED** [review]

**Comment by weaverryan** [comment]
Thanks @dmaicher and everyone else!

**Pull request merged**
