### PR TITLE
Fixing manifest paths (by temporarily embedding webpack-manifest-plugin fix)

### LINKED ISSUE #907: Version 1.0 problems in manifest.json when importing from composer vendor folder
Hello I'm trying to update sylius webpack encore to 1.0.3 but the manifest.json is all wrong, maybe it's because sylius entry point is a javascript that imports files from vendor?

This is the entry point. `sylius` is inside vendor.
```
import 'sylius/bundle/AdminBundle/Resources/private/entry';
```

and the content of manifest.json is this

```
{
  "build/shop/shop-entry.css": "/build/shop/shop-entry.css",
  "build/shop/shop-entry.js": "/build/shop/shop-entry.js",
  "build/shop/shop-entry.eot": "/build/shop/fonts/outline-icons.752905fa.eot",
  "build/shop/shop-entry.svg": "/build/shop/images/outline-icons.9c4845b4.svg",
  "build/shop/shop-entry.ttf": "/build/shop/fonts/outline-icons.53671035.ttf",
  "build/shop/shop-entry.woff": "/build/shop/fonts/outline-icons.ddae9b1b.woff",
  "build/shop/shop-entry.woff2": "/build/shop/fonts/outline-icons.687a4990.woff2",
  "build/shop/shop-entry.png": "/build/shop/images/logo.72a9465e.png",
  "build/shop/shop-entry.gif": "/build/shop/images/loading.f657825a.gif",
  "build/shop/shop-entry.jpg": "/build/shop/images/homepage-banner.8d8f072a.jpg",
  "build/shop/node_modules/semantic-ui-css/themes/default/assets/fonts/brand-icons.svg": "/build/shop/images/brand-icons.6729d297.svg",
  "build/shop/node_modules/semantic-ui-css/themes/default/assets/fonts/icons.svg": "/build/shop/images/icons.62d9dae4.svg",
  "build/shop/vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Resources/private/img/homepage-banner.jpg": "/build/shop/images/homepage-banner.8d8f072a.jpg",
  "build/shop/node_modules/semantic-ui-css/themes/default/assets/fonts/outline-icons.svg": "/build/shop/images/outline-icons.9c4845b4.svg",
  "build/shop/node_modules/semantic-ui-css/themes/default/assets/fonts/icons.eot": "/build/shop/fonts/icons.a01e3f2d.eot",
  "build/shop/node_modules/semantic-ui-css/themes/default/assets/fonts/icons.ttf": "/build/shop/fonts/icons.c656b8ca.ttf",
  "build/shop/node_modules/semantic-ui-css/themes/default/assets/fonts/brand-icons.eot": "/build/shop/fonts/brand-icons.d68fa3e6.eot",
  "build/shop/node_modules/semantic-ui-css/themes/default/assets/fonts/brand-icons.ttf": "/build/shop/fonts/brand-icons.65a2fb6d.ttf",
  "build/shop/node_modules/semantic-ui-css/themes/default/assets/fonts/brand-icons.woff": "/build/shop/fonts/brand-icons.cac87dc0.woff",
  "build/shop/node_modules/semantic-ui-css/themes/default/assets/fonts/brand-icons.woff2": "/build/shop/fonts/brand-icons.278156e4.woff2",
  "build/shop/node_modules/semantic-ui-css/themes/default/assets/fonts/icons.woff": "/build/shop/fonts/icons.425399f8.woff",
  "build/shop/vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Resources/private/img/sylius-plus-banner.png": "/build/shop/images/sylius-plus-banner.fff4fe72.png",
  "build/shop/node_modules/semantic-ui-css/themes/default/assets/fonts/icons.woff2": "/build/shop/fonts/icons.38c6d8ba.woff2",
  "build/shop/node_modules/semantic-ui-css/themes/default/assets/fonts/outline-icons.eot": "/build/shop/fonts/outline-icons.752905fa.eot",
  "build/shop/node_modules/semantic-ui-css/themes/default/assets/fonts/outline-icons.ttf": "/build/shop/fonts/outline-icons.53671035.ttf",
  "build/shop/node_modules/semantic-ui-css/themes/default/assets/images/flags.png": "/build/shop/images/flags.99f63ae7.png",
  "build/shop/vendor/sylius/sylius/src/Sylius/Bundle/UiBundle/Resources/private/img/logo.png": "/build/shop/images/logo.72a9465e.png",
  "build/shop/node_modules/semantic-ui-css/themes/default/assets/fonts/outline-icons.woff": "/build/shop/fonts/outline-icons.ddae9b1b.woff",
  "build/shop/node_modules/semantic-ui-css/themes/default/assets/fonts/outline-icons.woff2": "/build/shop/fonts/outline-icons.687a4990.woff2",
  "build/shop/node_modules/lightbox2/dist/images/loading.gif": "/build/shop/images/loading.f657825a.gif",
  "build/shop/vendor/sylius/sylius/src/Sylius/Bundle/UiBundle/Resources/private/img/avatar.png": "/build/shop/images/avatar.fa261429.png",
  "build/shop/node_modules/lightbox2/dist/images/prev.png": "/build/shop/images/prev.0edc57cc.png",
  "build/shop/node_modules/lightbox2/dist/images/next.png": "/build/shop/images/next.62074ac7.png",
  "build/shop/node_modules/lightbox2/dist/images/close.png": "/build/shop/images/close.0cfd6489.png"
}
```

Should be this

```{
  "build/shop/shop-entry.css": "/build/shop/shop-entry.css",
  "build/shop/shop-entry.js": "/build/shop/shop-entry.js",
  "build/shop/fonts/brand-icons.woff2": "/build/shop/fonts/brand-icons.278156e4.woff2",
  "build/shop/fonts/brand-icons.ttf": "/build/shop/fonts/brand-icons.65a2fb6d.ttf",
  "build/shop/fonts/brand-icons.woff": "/build/shop/fonts/brand-icons.cac87dc0.woff",
  "build/shop/fonts/brand-icons.eot": "/build/shop/fonts/brand-icons.d68fa3e6.eot",
  "build/shop/fonts/icons.woff2": "/build/shop/fonts/icons.38c6d8ba.woff2",
  "build/shop/fonts/icons.woff": "/build/shop/fonts/icons.425399f8.woff",
  "build/shop/fonts/icons.eot": "/build/shop/fonts/icons.a01e3f2d.eot",
  "build/shop/fonts/icons.ttf": "/build/shop/fonts/icons.c656b8ca.ttf",
  "build/shop/fonts/outline-icons.ttf": "/build/shop/fonts/outline-icons.53671035.ttf",
  "build/shop/fonts/outline-icons.woff2": "/build/shop/fonts/outline-icons.687a4990.woff2",
  "build/shop/fonts/outline-icons.eot": "/build/shop/fonts/outline-icons.752905fa.eot",
  "build/shop/fonts/outline-icons.woff": "/build/shop/fonts/outline-icons.ddae9b1b.woff",
  "build/shop/images/avatar.png": "/build/shop/images/avatar.fa261429.png",
  "build/shop/images/brand-icons.svg": "/build/shop/images/brand-icons.6729d297.svg",
  "build/shop/images/close.png": "/build/shop/images/close.0cfd6489.png",
  "build/shop/images/flags.png": "/build/shop/images/flags.99f63ae7.png",
  "build/shop/images/homepage-banner.jpg": "/build/shop/images/homepage-banner.8d8f072a.jpg",
  "build/shop/images/icons.svg": "/build/shop/images/icons.62d9dae4.svg",
  "build/shop/images/loading.gif": "/build/shop/images/loading.f657825a.gif",
  "build/shop/images/logo.png": "/build/shop/images/logo.72a9465e.png",
  "build/shop/images/next.png": "/build/shop/images/next.62074ac7.png",
  "build/shop/images/outline-icons.svg": "/build/shop/images/outline-icons.9c4845b4.svg",
  "build/shop/images/prev.png": "/build/shop/images/prev.0edc57cc.png",
  "build/shop/images/sylius-plus-banner.png": "/build/shop/images/sylius-plus-banner.fff4fe72.png"
}
```

### PR DESCRIPTION
**Pull request by weaverryan**
This temporarily embeds https://github.com/shellscape/webpack-manifest-plugin/pull/249, which fixes #907 and also a comment on https://github.com/symfony/webpack-encore/issues/914#issuecomment-773882092

To test this:

```
$ yarn remove @symfony/webpack-encore
$ yarn add git://github.com/weaverryan/webpack-encore.git#try-manifest-fix
```

Please let me know if this does or doesn't fix your `manifest.json` file. I'm also interested in hearing from Windows users, as the fix requires some "path" manipulation.

Thanks!

### CODE REVIEW

**Comment by minimit** [comment]
Works great on mac, can't test on windows

**Comment by weaverryan** [comment]
Thanks @shellscape for keeping an eye on that ;). I did include it in the new `webpack-manifest-plugin` directory - I grabbed the LICENSE file from `master` and put it there - https://github.com/symfony/webpack-encore/pull/921/files#diff-1422c8fd28cafc7a2c9bb9bfba27c0a1598d225ced0644653c1226bbd48604e7 - but let me know if it needs to be somewhere else.

Btw, this embedding I hope is temporary, at best :). I want to get the fix out to our users ASAP because I don't want users to start relying on the new incorrect paths... only for us to change them back later.

**Comment by weaverryan** [comment]
This is now ready to go. We may never merge it - it depends on https://github.com/shellscape/webpack-manifest-plugin/pull/249 - I'd like to merge and tag a fix ASAP for people. We could always remove this "embedded" plugin easily and re-add the real one.

Cheers!

**Comment by weaverryan** [comment]
I've fully embedded the fix from https://github.com/shellscape/webpack-manifest-plugin/pull/249

I'm confident that I now have the problem solved correctly there. I'd like to get this fix to our users, so I'm planning to merge this PR and temporarily embed the plugin so we can get it released :).

Cheers!

**Pull request merged**
