### PR TITLE
feat(node): drop support for node 11 (end-of-life since 1 year)

### PR DESCRIPTION
**Pull request by Kocal**
This PR is a proposal for the Node.js 11 support issue I encountered in #774.

### CODE REVIEW

**Comment by Rodrigo001-de** [comment]
Project made with TypeScript, react.Js, React-native. Recycling day design

https://github.com/Rodrigo001-de/Projeto-Ecoleta-advanced

**Comment by Lyrkan** [comment]
Thanks @Kocal

**Comment by Kocal** [comment]
I will rebase #774

**Comment by Kocal** [comment]
@weaverryan I think it should be great to document this breaking change in https://github.com/symfony/webpack-encore/releases/tag/v0.31.0, WDYT?

**Pull request merged**
