### PR TITLE
[Dependencies] Update postcss-loader to use latest v3 release

### PR DESCRIPTION
**Pull request by royklutman**

### CODE REVIEW

**Comment by stof** [comment]
@Lyrkan if we don't change it, we don't test either what happens for people using v3, and anyone doing a `yarn add postcss-loader` today would get v3, not v2.

**Comment by Lyrkan** [comment]
Yep, as I said it probably isn't a big issue for that one if it is included in the Webpack 4 release since it already has other BC breaks, my change request was mostly motivated by the missing `yarn.lock` update.

That being said, I just realized that Encore probably won't allow older version with the new `ensurePackagesExistAndAreCorrectVersion` check anyway. So, the only remaining question is: in the future should we only allow to change dev dependencies versions during major updates since it may cause BC breaks?

**Comment by royklutman** [comment]
@Lyrkan I added the `yarn.lock` file, can you have a quick look to verify it looks okay?

**Comment by Lyrkan** [comment]
Seems right :)

**Comment by Lyrkan** [comment]
Thank you @royklutman

**Pull request merged**
