### PR TITLE
Allowing new major versions of outdated dependencies

### LINKED ISSUE #1029: Upgrade dependencies!
Listing by `npm-check-updates`:
```
 @babel/plugin-proposal-class-properties                                   ^7.0.0  →   ^7.14.5
 @babel/plugin-transform-react-jsx                                         ^7.0.0  →   ^7.14.9
 @babel/preset-react                                                       ^7.0.0  →   ^7.14.5
 @babel/preset-typescript                                                  ^7.0.0  →   ^7.15.0
 @symfony/stimulus-bridge                                        ^1.1.0 || ^2.0.0  →    ^2.1.0
 @vue/babel-helper-vue-jsx-merge-props                                     ^1.0.0  →    ^1.2.1
 @vue/babel-preset-jsx                                                     ^1.0.0  →    ^1.2.4
 @vue/compiler-sfc                                                         ^3.0.2  →    ^3.2.6
 autoprefixer                                                             ^10.2.0  →   ^10.3.3
 babel-eslint                                                             ^10.0.1  →   ^10.1.0
 chai                                                                      ^4.2.0  →    ^4.3.4
 core-js                                                                   ^3.0.0  →   ^3.16.4
 eslint                                                          ^6.7.0 || ^7.0.0  →   ^7.32.0
 eslint-loader                                                             ^4.0.0  →    ^4.0.2
 eslint-plugin-header                                                      ^3.0.0  →    ^3.1.1
 eslint-plugin-import                                                      ^2.8.0  →   ^2.24.2
 file-loader                                                               ^6.0.0  →    ^6.2.0
 fork-ts-checker-webpack-plugin                                  ^5.0.0 || ^6.0.0  →    ^6.3.2
 fs-extra                                                                  ^9.0.0  →   ^10.0.0
 handlebars-loader                                                         ^1.7.0  →    ^1.7.1
 http-server                                                              ^0.12.3  →   ^13.0.1
 less                                                                      ^4.0.0  →    ^4.1.1
 less-loader                                           ^7.0.0 || ^8.0.0 || ^9.0.0  →   ^10.0.1
 mocha                                                                     ^8.2.1  →    ^9.1.1
 postcss                                                                   ^8.1.0  →    ^8.3.6
 postcss-loader                                                  ^4.0.0 || ^5.0.0  →    ^6.1.1
 preact                                                         ^8.2.1 || ^10.0.0  →  ^10.5.14
 preact-compat                                                            ^3.17.0  →   ^3.19.0
 sass                                                                     ^1.17.0  →   ^1.38.2
 sass-loader                              ^9.0.1 || ^10.0.0 || ^11.0.0 || ^12.0.0  →   ^12.1.0
 sinon                                                                     ^9.0.2  →   ^11.1.2
 strip-ansi                                                                ^6.0.0  →    ^7.0.0
 stylus                                                                   ^0.54.5  →   ^0.54.8
 stylus-loader                                         ^3.0.2 || ^4.0.0 || ^5.0.0  →    ^6.1.0
 ts-loader                                                       ^8.0.1 || ^9.0.0  →    ^9.2.5
 typescript                                                               >=3.6.3  →   >=4.4.2
 vue-template-compiler                                                       ^2.5  →      ^2.6
 webpack-notifier                                                          ^1.6.0  →   ^1.13.0
 @babel/core                                                               ^7.7.0  →   ^7.15.0
 @babel/plugin-syntax-dynamic-import                                       ^7.0.0  →    ^7.8.3
 @babel/preset-env                                                        ^7.10.0  →   ^7.15.0
 assets-webpack-plugin                                                      7.0.*  →     7.1.*
 chalk                                                                     ^4.0.0  →    ^4.1.2
 css-loader                                                                ^5.2.4  →    ^6.2.0
 css-minimizer-webpack-plugin                                              ^2.0.0  →    ^3.0.2
 mini-css-extract-plugin                                                   ^1.5.0  →    ^2.2.0
 pretty-error                                                              ^3.0.3  →    ^3.0.4
 resolve-url-loader                                                        ^3.1.2  →    ^4.0.0
 semver                                                                    ^7.3.2  →    ^7.3.5
 style-loader                                                              ^2.0.0  →    ^3.2.1
 terser-webpack-plugin                                                     ^5.1.1  →    ^5.1.4
 webpack                                                                    ^5.35  →     ^5.51
 webpack-dev-server                                                 ^4.0.0-beta.0  →    ^4.0.0
 yargs-parser                                                             ^20.2.4  →   ^20.2.9
```

### PR DESCRIPTION
**Pull request by weaverryan**
Fixes #1029

~~A bit more work to do. For now, I'm focused only on the main dependencies (not the `devDependencies`).~~

~~You could argue that this will require a new major version of webpack-encore. However, there is a precedence for allowing major dependency upgrades on minor versions in the past: https://github.com/symfony/webpack-encore/releases/tag/v1.2.0. Assuming none of the libraries have underlying changes that are likely to affect users, I'd like to do that again.~~ Edit: likely we should have a new major release.

## Dependencies

* ~`chalk`~: kept at v4 because v5 requires esm. v4 is stable.
* `clean-webpack-plugin`: `3->4` No breaking changes
* `css-loader`: `5->6`: Min node to 12.3.0,  other changes: [CHANGELOG](https://github.com/webpack-contrib/css-loader/blob/master/CHANGELOG.md#-breaking-changes)
* `css-minimizer-webpack-plugin`: `2->3` Min node to 12.3.0
* `loader-utils`: REMOVED
* mini-css-extract-plugin `1.5->2.2.1` Min node to 12.13.0, Webpack to 5.0.0, other changes: [CHANGELOG](https://github.com/webpack-contrib/mini-css-extract-plugin/blob/master/CHANGELOG.md#-breaking-changes) 
- ~`pkg-up`~: Keeping version `3.1` because `4` requires esm.
- `pretty-error`: `3.0->4.0` Min node to 12.0 
- `resolve-url-loader` `3.0->5.0` Min node to 12.0, postcss ^8.0, remove `rework` engine,  other changes: [CHANGELOG](https://github.com/bholloway/resolve-url-loader/blob/v4-maintenance/packages/resolve-url-loader/CHANGELOG.md)
- `style-loader`: `2->3` Min node to 12.13, Min webpack to 5.0 other changes: [CHANGELOG](https://github.com/webpack-contrib/style-loader/blob/master/CHANGELOG.md#-breaking-changes)
- `yargs-parser`: `20.2->21` Min node to 12.0

## Dev Dependencies
- `eslint`: `7->8` Min node to `12.22`
- `eslint-webpack-plugin`: `2.5->3` min node to `12`. Min webpack `5`
- `fork-ts-checker-webpack-plugin`: `5->6` [CHANGELOG](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/releases/tag/v6.0.0)
- `fs-extra`: `9->10` Min node to `12`. Potentially breaking changes: [CHANGELOG](https://github.com/jprichardson/node-fs-extra/blob/master/CHANGELOG.md#breaking-changes****)
- `http-server`: `0.12->14` Min node to `12`.
- `less-loader`: `7->10`: Min node to `12`. Min webpack to `5`. `less.webpackLoaderContext` was removed, please use `pluginManager.webpackLoaderContext`
- `mocha`: `8->9`: min node to `12`. [CHANGELOG](https://github.com/mochajs/mocha/blob/master/CHANGELOG.md#boom-breaking-changes)
- `postcss-loader`: `4-5->6`: min node to `12`. min webpack to `5`.
- `preact`: `8->10`: [CHANGELOG](https://github.com/preactjs/preact/releases/tag/10.0.0)
- `sass-loader`: `9-10-11->12` min node to `12.13`. Min webpack to `5`
- `sinon`: `9->12`
- ~`strip-ansi`~: Need to keep `6` because `7` is esm only. Min node to `12`
- `stylus`: `0.54->0.56`
- `stylus-loader`: `3-4-5->6`: Min node to `12.13`. Min webpack to `5`. Other breaking changes: [CHANGELOG](https://github.com/webpack-contrib/stylus-loader/blob/master/CHANGELOG.md#400-2020-09-29)
* `vue-loader`: `16-17` No important changes: https://github.com/vuejs/vue-loader/blob/next/CHANGELOG.md#1700-2021-12-12

TODOs:

* [x] A) Check CHANGELOG of each library to see what changes, if any, we need.
* [x] B) Bump *our* CHANGELOG for changes people should watch out for
* [x] C) Get tests passing

### CODE REVIEW

**Comment by TropicalRaisel** [comment]
Based on [Webpack's changelogs](https://github.com/webpack/webpack/releases?after=v5.38.1), there shouldn't be anything that stops jumping from `5.35` to `5.51.1`.

**Comment by stof** [comment]
@weaverryan what is the state of this ?

**Comment by shadowc** [comment]
More info about `devDependencies`:

- `eslint`: `7->8` Min node to `12.22`
- `eslint-webpack-plugin`: `2.5->3` min node to `12`. Min webpack `5`
- `fork-ts-checker-webpack-plugin`: `5->6` [CHANGELOG](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/releases/tag/v6.0.0)
- `fs-extra`: `9->10` Min node to `12`. Potentially breaking changes: [CHANGELOG](https://github.com/jprichardson/node-fs-extra/blob/master/CHANGELOG.md#breaking-changes****)
- `http-server`: `0.12->14` Min node to `12`.
- `less-loader`: `7->10`: Min node to `12`. Min webpack to `5`. `less.webpackLoaderContext` was removed, please use `pluginManager.webpackLoaderContext`
- `mocha`: `8->9`: min node to `12`. [CHANGELOG](https://github.com/mochajs/mocha/blob/master/CHANGELOG.md#boom-breaking-changes)
- `postcss-loader`: `4-5->6`: min node to `12`. min webpack to `5`.
- `preact`: `8->10`: [CHANGELOG](https://github.com/preactjs/preact/releases/tag/10.0.0)
- `sass-loader`: `9-10-11->12` min node to `12.13`. Min webpack to `5`
- `sinon`: `9->12`
- ~`strip-ansi`~: Need to keep `6` because `7` is esm only. Min node to `12`
- `stylus`: `0.54->0.56`
- `stylus-loader`: `3-4-5->6`: Min node to `12.13`. Min webpack to `5`. Other breaking changes: [CHANGELOG](https://github.com/webpack-contrib/stylus-loader/blob/master/CHANGELOG.md#400-2020-09-29)

**Comment by weaverryan** [comment]
This is now ready!

**Pull request merged**
